### ISSUE TITLE
variant does not support 64 bit integer

### ISSUE THREAD

**Issue by edsiper** [fluent/cfl#4]
open for discussion: should variant interface support 64 bit integers ? cc: @leonardo-albertovich

**Comment by leonardo-albertovich** [comment]
I don't se a reason not to, it was an oversight on my side when I first implemented it since I was following OTLPs AnyType structure and that one uses `int64_t` for ingeters.

**Comment by edsiper** [comment]
got it, I will move it to int64, thanks

**Comment by edsiper** [comment]
fixed with #5
